# TODO: Make pre-commit.nix instead?
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        pass_filenames: false
        types: [rust]
      # TODO: Revive when the time is right!
      # - id: cargo-clippy
      #   name: cargo clippy
      #   entry: cargo clippy --all-targets
      #   language: system
      #   pass_filenames: false
      #   types: [rust]
