services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     # - DATABASE_URL=postgresql://POSTGRES_USER:POSTGRES_PASSWORD@localhost:5432/POSTGRES_DB
  #     - DATABASE_URL=postgresql://myuser:mysecretpassword@localhost:5432/myapp
  #   volumes:
  #     - .:/app
  #   working_dir: /app

volumes:
  postgres-data:
